/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreedImage: typeof import('./components/breed-image/BreedImage.vue')['default']
    CatCard: typeof import('./components/cat-card/CatCard.vue')['default']
    Empty: typeof import('./components/empty/Empty.vue')['default']
    NavBar: typeof import('./components/nav-bar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBar: typeof import('./components/score-bar/ScoreBar.vue')['default']
  }
}

// For TSX support
declare global {
  const BreedImage: typeof import('./components/breed-image/BreedImage.vue')['default']
  const CatCard: typeof import('./components/cat-card/CatCard.vue')['default']
  const Empty: typeof import('./components/empty/Empty.vue')['default']
  const NavBar: typeof import('./components/nav-bar/NavBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScoreBar: typeof import('./components/score-bar/ScoreBar.vue')['default']
}